Repository ember-template-lint/ember-template-lint-plugin-prettier, pull requests merged in 2021-11, with the labels that each got.

#176 Drop support for Node 10 and 15
  .github/workflows/ci.yml
  package.json
Labels: breaking

#178 Ensuring we pass node and/or line, column, endLine, endColumn to log
  lib/rules/prettier.js
  test/unit/rules/lint-prettier-test.js
Labels: enhancement

#179 Setup release-it with `yarn create rwjblue-release-it-setup`
  RELEASE.md
  package.json
  yarn.lock
Labels: internal
